FROM deersheep330/python-chrome-crontab

ENV TZ=Asia/Taipei

WORKDIR /home/app

COPY requirements.txt .

RUN pip install -r requirements.txt

COPY ./booking ./booking
COPY ./test.py .

# Run the command on container startup
CMD /usr/local/bin/python /home/app/test.py
